### ISSUE TITLE
Error sending notification to opsgenie

### ISSUE THREAD

**Issue by vibhory2j** [getsentry/sentry-opsgenie#11]
I'm getting an error sending notification to opsgenie from Sentry project. Below is a error message seen in the logs. Have double checked that the API key and other configurations and they appear to be fine to me. In fact able to POST alert to opsgenie via curl using same configurations. I'm using version 0.1.0 of the plugin.

```
Exception: Unsuccessful response from OpsGenie: {u'message': u'Could not authenticate', u'took': 0.0, u'requestId': u'fc477320-6770-47b0-8eff-9c588f78bada'}\n
```

Any idea on this? Could this be a bug.

**Comment by markstory** [comment]
That looks like a response from opsgenie, so not much we can do to fix that. You could add additional logging to ensure that your credentials are correct when they make their way into the plugin code.

**Comment by vibhory2j** [comment]
I believe the problem we were facing was due to installing sentry-opsgenie via regular pip install. Changed it to `https://github.com/getsentry/sentry-opsgenie/archive/master.zip` and then the notifications were sent successfully. In case somebody else faces the same problem it is worth checking how the plugin is installed.
