### ISSUE TITLE
Allow filtering by environment

### ISSUE THREAD

**Issue by jeffkimble** [getsentry/sentry-opsgenie#6]
The opsgenie integration does not allow keyword or environment filtering.  This is critical to support migration to Sentry 9 with single projects.   It won't do to generate opsgenie alerts for non-production environments.

**Comment by dcramer** [comment]
You can simply change your rules to restrict the environment.

![screen shot 2018-09-18 at 12 50 06 pm](https://user-images.githubusercontent.com/23610/45712514-682f5180-bb41-11e8-851e-b620b095f1bc.png)
